<?php

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

/** 
 * @file
 * This file demenstrates how to use hook functions in Drupal.
 */


/**
 * hook_cron()
 */
function mymodule_cron() {
  \Drupal::messenger()->addMessage("This is my custom module cron hook function.");
}

/**
 * hook_form_alter()
 */
function mymodule_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  \Drupal::messenger()->addMessage("form_id for this form is: $form_id");
  if ($form_id == 'node_article_edit_form') {
    $form['actions']['submit']['#value'] = 'Dont forget to save me!';
  }
}

/**
 * hook_getNFL()
 *
 */
function mymodule_getNFL() {
  $client = \Drupal::httpClient();
  $request = $client->get('https://odds.p.rapidapi.com/v4/sports/americanfootball_nfl/scores',
    [
      'headers' => [
        'X-RapidAPI-Key' => $API_KEY,
        'X-RapidAPI-Host' => 'odds.p.rapidapi.com',
      ],
      'query' => [
        'daysFrom' => '3'
      ]
    ]);
  $response = $request->getBody();
  $data = json_decode($response, TRUE);
  echo $data;
}